FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 7860

CMD sh -c "python backend_api.py & streamlit run dashboard.py --server.address=0.0.0.0 --server.port=7860"